# Generated by Django 5.0.6 on 2024-06-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_products_price'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='varint',
            new_name='Variant',
        ),
    ]
