# Generated by Django 5.0.6 on 2024-06-09 17:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_alter_variant_options_alter_variant_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ProductImage',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='subvariant',
            name='parent',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_variants', to='products.variant'),
        ),
        migrations.AlterField(
            model_name='subvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_variants_product', to='products.products'),
        ),
        migrations.AlterField(
            model_name='subvariant',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='variant',
            name='stock',
            field=models.IntegerField(default=0),
        ),
    ]
