# Generated by Django 5.0.6 on 2024-06-09 18:50

import versatileimagefield.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_products_productimage_alter_subvariant_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='ProductImage',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
